require 'rubygems'
require 'rake/gempackagetask'
require 'spec/rake/spectask'

require 'merb-core'
require 'merb-core/tasks/merb'
require 'merb-core/test/tasks/spectasks'

GEM_NAME = "mui-password"
AUTHOR = "Jamie Hoover"
EMAIL = "dont.tase@me.com"
HOMEPAGE = "http://uipoet.com/"
SUMMARY = "Password protection for Merb."
GEM_VERSION = "1.0"

spec = Gem::Specification.new do |s|
  s.rubyforge_project = "mui"
  s.name = GEM_NAME
  s.version = GEM_VERSION
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE"]
  s.summary = SUMMARY
  s.description = s.summary
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  s.add_dependency('mui-core', '>= 1.0')
  s.add_dependency('dm-core', '>= 0.9.6')
  s.add_dependency('dm-migrations', '>= 0.9.6')
  s.add_dependency('dm-validations', '>= 0.9.6')
  s.add_dependency('data_objects', '>= 0.9.6')
  s.add_dependency('do_sqlite3', '>= 0.9.6')
  s.add_dependency('merb_datamapper', '>= 0.9.8')
  s.require_path = 'lib'
  s.files = %w(LICENSE README Rakefile) + Dir.glob("{lib,app}/**/*")
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

desc "Install the gem"
task :install do
  Merb::RakeHelper.install(GEM_NAME, :version => GEM_VERSION)
end

desc "Uninstall the gem"
task :uninstall do
  Merb::RakeHelper.uninstall(GEM_NAME, :version => GEM_VERSION)
end

desc "Create a gemspec file"
task :gemspec do
  File.open("#{GEM_NAME}.gemspec", "w") do |file|
    file.puts spec.to_ruby
  end
end

desc "Run all examples (or a specific spec with TASK=xxxx)"
Spec::Rake::SpecTask.new('spec') do |t|
  t.spec_opts  = ["-cfs"]
  t.spec_files = begin
    if ENV["TASK"] 
      ENV["TASK"].split(',').map { |task| "spec/**/#{task}_spec.rb" }
    else
      FileList['spec/**/*_spec.rb']
    end
  end
end

desc 'Default: run spec examples'
task :default => 'spec'